# Generated by Django 5.0 on 2023-12-11 01:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_day_thyme_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onedaythyme',
            name='prompts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), default=list, size=None),
        ),
    ]
