# Generated by Django 5.0 on 2023-12-11 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_day_thyme_app', '0002_onedaythyme_prompts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onedaythyme',
            name='day',
        ),
    ]
