# Generated by Django 5.0 on 2023-12-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one_day_thyme_app', '0003_remove_onedaythyme_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='onedaythyme',
            name='day',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
