# Generated by Django 5.0 on 2023-12-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_app', '0002_remove_entry_game_profile_alter_entry_posted_date_and_more'),
        ('one_day_thyme_app', '0004_onedaythyme_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onedaythyme',
            name='entries',
            field=models.ManyToManyField(blank=True, to='entry_app.entry'),
        ),
    ]
