# Generated by Django 5.0 on 2023-12-05 03:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_app', '0001_initial'),
        ('profile_app', '0002_gameprofile_user_alter_gameprofile_game_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='game_profile',
        ),
        migrations.AlterField(
            model_name='entry',
            name='posted_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='entry',
            name='game_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='profile_app.gameprofile'),
        ),
    ]
