# Generated by Django 5.0 on 2023-12-05 21:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alone_stars_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aloneamongstars',
            name='prompts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), default=[], size=None),
        ),
    ]
