# Generated by Django 5.0 on 2023-12-05 03:13

import django.db.models.deletion
import profile_app.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameprofile',
            name='game_name',
            field=models.CharField(validators=[profile_app.validators.validate_game_name]),
        ),
    ]
