# Generated by Django 5.0 on 2023-12-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_gameprofile_user_alter_gameprofile_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprofile',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
